### ISSUE TITLE
[Feature] Add /rename and /lore prefix and suffixes that can be set in the config

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#141]
Idea for config:
```
prefixes:
   rename: ''
   lore: ''
suffixes:
```

Requested by @Remski on spigotmc.org.
https://www.spigotmc.org/conversations/something.411686/message?message_id=2147055

**Comment by JustBru00** [comment]
```
# Command arguments prefixes and suffixes
command_argument:
  prefixes:
    rename: ''
  suffixes:
    rename: ''
    ```
