### ISSUE TITLE
How do I show the renamed item name in the success message to the player? How do I disable bypass chat messages?

### ISSUE THREAD

**Issue by Tolmwn** [JustBru00/RenamePlugin#181]
Hey guys, i want to ask how can i take off this two things from the blacklists
![image](https://github.com/JustBru00/RenamePlugin/assets/136921445/57a1dc67-07cd-45c2-b8ff-b20cc87d0a0d)

and how can i put when ppl raname items that get a private chat msg that say:  &aYou have succefully renamed your item to (newname) 

this is my blacklists, i delete the text but at the chat its like the screenshot
blacklists:
  material:
    bypass: ''
  text:
    bypass: ''
  existingname:
    bypass: '&aYou just bypassed the existing name blacklist.'
  existinglore:
    bypass: '&aYou just bypassed the existing lore blacklist.'

**Comment by JustBru00** [comment]
You can display the new name that a player just added to their item using `{new_name}`.

Example:
```Yml
rename:
  success: '&aYou successfully renamed your item to &f"{new_name}&f"&a.'
  log: '&aThe player &f{player} &ajust renamed an item to: &f"{name}&f"&a.'
  ```

If you would like to disable bypass messages change `disable_bypass_messages` in the config.yml file to `true`.

Example:
```Yml
disable_bypass_messages: true
```
